# This make file is to be added by the Makefile at the main directory

SCFENCE_LOCAL := scgen.o inference.o inferset.o inferlist.o patch.o scfence.o

SCFENCE_OBJS := $(SCFENCE_LOCAL:%=$(SCFENCE_DIR)/%)

OBJECTS += $(SCFENCE_OBJS)
