FENCE_LOCAL := $(SCFENCE_DIR)/scgen.o \
	$(SCFENCE_DIR)/inference.o \
	$(SCFENCE_DIR)/inferset.o \
	$(SCFENCE_DIR)/inferlist.o \
	$(SCFENCE_DIR)/patch.o \
	$(SCFENCE_DIR)/scfence.o

FENCE_OBJS := $(FENCE_LOCAL:%=$(FENCE_DIR)/%)

OBJECTS += $(FENCE_OBJS)
